# To run below docker compose command:
#   > docker compose up -d --build
#


services:
  jenkins-blueocean:
    build:
      context: .
      dockerfile: Dockerfile
    image: myjenkins-blueocean:2.440.3
    container_name: jenkins-blueocean
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - jenkins

    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:




